DROP TABLE IF EXISTS boats CASCADE;
DROP TABLE IF EXISTS voyages;

CREATE TABLE boats(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  style TEXT NOT NULL,
  color TEXT NOT NULL,
  powered TEXT NOT NULL
);

CREATE TABLE voyages (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  duration INTEGER CHECK (duration > 0),
  boat_id BIGINT REFERENCES boats(id)
);